---
# Source: superset/templates/secret-env.yaml
apiVersion: v1
kind: Secret
metadata:
  name: local-superset-env
  namespace: default
  labels:
    app: local-superset
    chart: superset-0.10.5
    release: "local"
    heritage: "Helm"
type: Opaque
stringData:
    REDIS_HOST: "local-redis-headless"
    REDIS_PORT: "6379"
    DB_HOST: "local-postgresql"
    DB_PORT: "5432"
    DB_USER: "superset"
    DB_PASS: "superset"
    DB_NAME: "superset"
