---
# Source: superset/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: local-superset
  namespace: default
  labels:
    app: superset
    chart: superset-0.10.5
    release: local
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8088
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: superset
    release: local
