---
# Source: superset/templates/secret-env.yaml
apiVersion: v1
kind: Secret
metadata:
  name: superset-env
  namespace: default
  labels:
    app: superset
    chart: superset-0.10.8
    release: "superset"
    heritage: "Helm"
type: Opaque
stringData:
    REDIS_HOST: "superset-redis-headless"
    REDIS_PORT: "6379"
    DB_HOST: "superset-postgresql"
    DB_PORT: "5432"
    DB_USER: "superset"
    DB_PASS: "superset"
    DB_NAME: "superset"
